---
title: 'codyn: an R package of community dynamics metrics'
author: Lauren M. Hallett, Sydney K. Jones,  Andrew A. MacDonald,  Matthew B. Jones,
  Dan F. B. Flynn, Peter Slaughter, Corinna Gries, Scott L. Collins
date: '`r Sys.Date()`'
output: word_document
bibliography: biblio.bib
---

##Abstract

##Introduction
As long-term datasets increase in scope and length, new analytical tools are being developed to capture patterns of species interactions over time. This has the potential to vastly expand our understanding of ecology. For example, many traditional measurements of community structure, such as diversity indices and rank-abundance curves, represent 'snapshots in time' that poorly capture community dynamics. In contrast, the development of related but temporal metrics, such as species turnover and rank shifts, has highlighted how much communities can vary over time. Similarly, species dynamics can affect the stability of community properties. A growing number of synthesis studies have applied new metrics to long-term datasets to test what factors influence the stability of ecosystems. As ecological records continue to grow and data storage and sharing barriers diminish, it is likely that these types of long-term studies will underpin many new advances in ecology.

However, there are several impediments to the broad adoption of temporal analyses by the ecological community. First, many metrics of community dynamics have not yet been published as functions in R. Although R is becoming the programming language of choice for most ecologists, the majority of ecologists rely on published instead of self-written functions. The primary R package for vegetation analyses, vegan, includes many diversity indices and ordination techniques but does not include temporal metrics of community patterns. Second, most temporal metrics are applied to datasets that include spatial as well as temporal replication. This adds an additional layer of complexity that may stall their general use and application. Third, many metrics of temporal dynamics are actively being developed, and so ecologists may be unfamiliar with the metrics available and their pros and cons.

Here we present a new R package, `codyn`, that fills this niche for published functions that characterize communities over time. Short for “community dynamics,” `codyn` functions are explicitly temporal and can be easily implemented over multiple spatial replicates. Functions in `codyn` fall into two categories: temporal diversity indices and community stability metrics. Below we describe the metrics by category and demonstrate their application with an example for the Konza Prairie Long-Term Ecological Research Site, Manhattan KS.

##Temporal diversity indices
The diversity indices in `codyn` are temporal analogs to traditional diversity indices such as richness and rank-abundance curves. They include species turnover (`turnover`), mean shifts in rank abundance (`mean_rank_shift`) [@Collins2008] and rate of directional change in community composition over time (`rate_change`). The associated vignette also includes a demonstration of 

### Species turnover
Species turnover represents a temporal analog to species richness  [@MacArthur1963; @diamond1969; @Collins2008; @cleland2013]. The function `turnover` calculates three metrics of species turnover: total turnover, appearances, and disappearances.The default metric `total` refers to total turnover, which calculates the proportion of species that differ between timepoints as:

$$ Total\; turnover = \frac{Species\; gained\; +\; Species\; lost}{Total\; species\; observed\; in\; both\; time points} $$

The `turnover` function includes the option to calculate only species appearances or only disappearances, because a time point in which many species appear may reflect a different ecological story than a time point in which many species drop from the system, but the total turnover in both scenarios may be similar. 

### Mean rank shifts
Mean rank shifts represent a temporal analog of species rank abundance distributions and indicate the degree of species reording between two time points [@Collins2008]. This metric is calculated by the `mean_rank_shift` function as:

$$ MRS = {\sum_{i=1}^{N} (|R_i,t+1 - R_i,t|})/N $$

where $N$ is the number of species in common in both time points, $t$ is the time point, $R_i,t$ is the relative rank of species $i$ in time $t$.

### Rate of community change
The `rate_change` function provides a measure of the rate and direction of change in a community. Community compositional changes are described by Euclidean distances, which are calculated on pair-wise communities across the entire time series. For example, a data set with 6 time intervals will have distance values for five one-interval time lags (e.g., time 1 vs time 2, time 2 vs time 3 ...), four two-interval time lags (e.g., time 1 vs time 3, time 2 vs time 4 ...) and so forth. These distance values are regressed against the time lag interval. The slope of this relationship indicates the rate and direction of community change [@collins2000].

##Community stability metrics
Ecologists have long debated the relationship between species diversity and stability. Unstable species populations may stabilize aggregate community properties if a decrease in one species is compensated for by an increase in another. In a time series, this should be reflected by a pattern in which species negatively covary or fluctuate asynchronously while total community stability remains relatively stable. `codyn` includes a function to characterize community stability, `community_stability`, and three metrics to characterize species covariance (`variance_ratio`) and asynchrony (`synchrony` with two options).

### Community stability
The `community_stability` function aggregates species abundances within replicate and time period, and uses these values to calculate community stability as the temporal mean divided by the temporal standard deviation [@tilman1999].

### Variance ratio
The variance ratio was one of the first metrics to characterize patterns of species covariance [@schluter1984] and was used in an early synthesis paper of species covariance in long time series [@houlahan2007]. The metric compares the variance of the community ($C$) as a whole relative to the sum of the individual population ($x_i$) variances:


$$ VR = \frac{Var(C)}{\sum_{i}^{N} Var(x_i)} $$

where:

$$ Var(C)  = \sum_{i = 1}^{N} Var(x_i) + 2\left(\sum_{i = 1}^{N - 1} \sum_{j = i + 1}^{N} Covar(x_i, x_j)\right) $$ 


If species vary independently then the variance ratio will be close to 1. A variance ratio  < 1 indicates predominately negative species covariance, whereas a variance ratio > 1 indicates that species generally positively covary. 

#### Significance testing
The variance ratio remains widely used but has been subject to a number of criticisms. Importantly, early uses of the variance ratio either did not include significance tests, or tested significance by comparing observed values to those returned by scrambling each species' time series. Null models using fully-scrambled species time series can generate spurious null expectations of covariance because the process disrupts within-species autocorrelation. Phase-scrambling [@Grman2010] and a temporal modification of the torus-translation [@hallett2014; adapted from @harms2001] have been used to address this issue. 

The `variance_ratio` function uses the temporal torus translation to conduct null modeling for significance tests. In this method a starting time point is randomly selected for each species' time series. This generates a null community matrix in which species abundances vary independently but within-species autocorrelation is maintained (for each species, the time series is disrupted only once). `codyn` also includes the option to apply the temporal torus translation for other test statistics using the `temporal_torus_translation` function, which returns the output of a user-specified function when applied to a null community for functions that require a species x time matrix and the `temporal_torus_translation_CI`, which returns  confidence intervals for a user-specified function that returns a single-value test statistic and requires a species x time matrix.

### Synchrony Option 1: "Loreau"
Loreau and de Mazancourt (2008) developed a metric of species synchrony that compares the variance of aggregated species abundances with the summed variances of individual species:

$$ Synchrony = \frac{{\sigma_(x_T)}^{2}}{({\sum_{i} \sigma_(x_i)})^{2}}$$

where:

$$ x_T(t) = {\sum_{i=1}^{N} x_i(t))} $$

This measure of synchrony is standardized between 0 (perfect asynchrony) and 1 (perfect synchrony) and is the default calculation in the `synchrony` function. A virtue of this metric is that it can be applied across communities of variable species richness. It can also be applied not only to species abundance but also population size and per capita growth rate. However, unlike the variance ratio it does not lend itself to significance testing. 

### Synchrony Option 2: "Gross"
Gross et al. (2014) developed a metric of synchrony that compares the average correlation of each individual species with the rest of the aggregated community:

$$ Synchrony = (1/N){{\sum_{i}Corr(x_i, \sum_{i\neq{j}}{x_j})}}$$

This measure of synchrony is standardized from -1 (perfect asynchrony) to 1 (perfect synchrony) and is centered at 0 when species fluctuate independently. It can be specified in the `synchrony` function. A virtue of this metric is it not sensitive to richness and has the potential for null-model significance testing. It may under-perform on short time series because it is based on correlation, and care should be taken when applying it to communities that contain very stable species (i.e., whose abundances do not change throughout the time series).

Qualititively, the degree to which the synchrony metrics calculated by `Loreau` versus `Gross` will differ depends on the abundance distributions of the species in a community. The `Loreau` method and the variance ratio are both based on variances, and are therefore more heavily influenced by abundant species. In contrast,  the `Gross` method is based on correlation and consequently weights species equally.

##Literature cited
